In [4]:
import numpy as np


# space checking




In [5]:
lst =range(1000)

In [6]:
lst

range(0, 1000)

In [7]:
import sys


In [8]:
sys.getsizeof(4)*len(lst)

28000

In [9]:
arr = np.arange(1000)

In [10]:
arr.size*arr.itemsize

4000

# CREATING ARRAY


In [11]:
a= np.array([1,2,3,4,5])

In [12]:
a

array([1, 2, 3, 4, 5])

In [13]:
a.ndim

1

In [14]:
a=np.array([[1,2,3],[4,5,6]])

In [15]:
a

array([[1, 2, 3],
       [4, 5, 6]])

In [16]:
a.ndim

2

# ones and zeros


In [17]:
var = np.zeros(10)

In [18]:
var

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [19]:
var = np.ones((3,4,5))  #3dimensions 4 rows 5 elements in each row
var

array([[[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]],

       [[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]]])

In [20]:
var.ndim

3

# functions


In [21]:
var=np.array([11,22,33,44])
var

array([11, 22, 33, 44])

In [22]:
type(var)

numpy.ndarray

In [23]:
var.argmax()    #max index position

3

In [24]:
var.argmin()

0

In [25]:
var.data

In [26]:
var.dtype

dtype('int32')

In [27]:
var.dtype.name

'int32'

In [28]:
var.itemsize

4

In [29]:
var

array([11, 22, 33, 44])

In [30]:
var[1]

22

In [31]:
var[0:2]

array([11, 22])

In [32]:
lst=[44,22,33]
lst

[44, 22, 33]

In [33]:
lst[0]=11
lst

[11, 22, 33]

In [34]:
var[0]=456
var

array([456,  22,  33,  44])

In [35]:
arr = np.array([[1,2,3,4],[6,7,8,9]], dtype = complex)


In [36]:
arr

array([[1.+0.j, 2.+0.j, 3.+0.j, 4.+0.j],
       [6.+0.j, 7.+0.j, 8.+0.j, 9.+0.j]])

In [37]:
#print an array with 10 values  by giving max and min
aa= np.linspace(0,2,10)
aa

array([0.        , 0.22222222, 0.44444444, 0.66666667, 0.88888889,
       1.11111111, 1.33333333, 1.55555556, 1.77777778, 2.        ])

In [38]:
np.sin(aa)

array([0.        , 0.22039774, 0.42995636, 0.6183698 , 0.77637192,
       0.8961922 , 0.9719379 , 0.99988386, 0.9786557 , 0.90929743])

In [39]:
np.tan(aa)

array([ 0.        ,  0.22595393,  0.47622143,  0.78684289,  1.23179859,
        2.01997033,  4.13172899, 65.60839711, -4.76215913, -2.18503986])

In [40]:
np.tanh(aa)

array([0.        , 0.21863508, 0.41732165, 0.58278295, 0.7108445 ,
       0.8044548 , 0.87006166, 0.9146975 , 0.94445565, 0.96402758])

In [41]:
from numpy import pi

In [42]:
pi

3.141592653589793

In [43]:
pi*aa

array([0.        , 0.6981317 , 1.3962634 , 2.0943951 , 2.7925268 ,
       3.4906585 , 4.1887902 , 4.88692191, 5.58505361, 6.28318531])

# RESHAPE AND RESIZE


In [44]:
a = np.arange(12)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

In [45]:
np.arange(12).reshape(4,3)

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11]])

In [46]:
a.reshape(12,1)

array([[ 0],
       [ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10],
       [11]])

In [47]:
rang = np.random.default_rng(2)

In [48]:
a = rang.random((3,4))
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [57]:
a.sum()  #sum of all the elements in the 'a'

4.682684022737332

In [50]:
a.sum(axis=0)  #sum of the each column

array([1.13668203, 1.68448469, 1.56439248, 0.29712483])

In [51]:
a.sum(axis=1) #sum of each row

array([1.46624496, 1.57170875, 1.64473031])

In [52]:
a.cumsum()

array([0.26161213, 0.56010328, 1.37432902, 1.46624496, 2.06634549,
       2.79490601, 2.98280709, 3.03795371, 3.31292308, 3.9703561 ,
       4.53262176, 4.68268402])

In [54]:
a.cumprod()


array([2.61612134e-01, 7.80889051e-02, 6.35819966e-02, 5.84419912e-03,
       3.50710696e-03, 2.55513970e-03, 4.80113492e-04, 2.64766398e-05,
       7.28026491e-06, 4.78628651e-06, 2.69116456e-06, 4.03842244e-07])

In [55]:
a.max()

0.8142257405942803

In [ ]:
q=567890

In [58]:
np.sqrt(q)

753.5847663003811

In [59]:
x=[1,2,3,4,5]


In [60]:
np.sqrt(x)

array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798])

In [61]:
np.log(x)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791])

In [62]:
np.exp(x)

array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
       148.4131591 ])

In [63]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

# TRANSPOSE

In [64]:
a.T

array([[0.26161213, 0.60010053, 0.27496937],
       [0.29849114, 0.72856053, 0.65743301],
       [0.81422574, 0.18790107, 0.56226566],
       [0.09191594, 0.05514663, 0.15006226]])

In [66]:
a.shape

(3, 4)

# REVERSE

In [68]:
a

array([[0.26161213, 0.29849114, 0.81422574, 0.09191594],
       [0.60010053, 0.72856053, 0.18790107, 0.05514663],
       [0.27496937, 0.65743301, 0.56226566, 0.15006226]])

In [79]:
aaa = np.linspace(1,4,10)

In [80]:
aaa

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [81]:
aab=np.array([[3,3,3],[4,4,4]])

In [82]:
ax = aab.sort(axis=0)

In [83]:
ax

In [84]:
aaa

array([1.        , 1.33333333, 1.66666667, 2.        , 2.33333333,
       2.66666667, 3.        , 3.33333333, 3.66666667, 4.        ])

In [88]:
aaa[-1]

4.0

In [89]:
aaa[-2]

3.6666666666666665

In [86]:
aaa[::-1]

array([4.        , 3.66666667, 3.33333333, 3.        , 2.66666667,
       2.33333333, 2.        , 1.66666667, 1.33333333, 1.        ])

In [87]:
np.floor(3.457)

3.0

In [90]:
np.abs(43.23490)

43.2349